[plugins]
# The kotlin version here is aligned to the Gradle embedded Kotlin version.
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

[libraries]
mockk = { group = "io.mockk", name = "mockk", version = "1.14.5" }
