[plugins]
# The kotlin version here is aligned to the Gradle embedded Kotlin version.
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version = "5.9.1" }
kotest-extensions-jvm = { module = "io.kotest:kotest-extensions-jvm", version = "5.9.1" }
mockk = { module = "io.mockk:mockk", version = "1.14.5" }
